name: keyboard_utils_fork_plus
description: fork from https://github.com/hello-coder-xu/keyboard_utils
version: 1.0.1
homepage: https://github.com/wolfe719/keyboard_utils.git

environment:
  sdk: "^3.4.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: br.com.keyboard_utils
        pluginClass: KeyboardUtilsPlugin
      ios:
        pluginClass: SwiftKeyboardUtilsPlugin
